export default {
  version: 8,
  name: "tilesStyle",
  light: { anchor: "viewport", color: "white", intensity: 0.3 },
  center: [113.46225800420783, 22.205729140373137],
  zoom: 17.4,
  bearing: 2.4,
  pitch: 45,
  sprite:
    "https://map-1258113332.cos.ap-guangzhou.myqcloud.com/sprites/outdoor/sprite?host=t.locnavi.com&t=1655975013375",
  glyphs:
    "https://map-1258113332.cos.ap-guangzhou.myqcloud.com/fonts/{fontstack}/{range}.pbf?host=t.locnavi.com&t=1655975013375",
  sources: {
    "1": {
      type: "vector",
      maxzoom: 19,
      tiles: [
        "https://map-1258113332.cos.ap-guangzhou.myqcloud.com/tiles_gcj02/珠海测试/1/{z}/{x}/{y}.pbf?version=1655974980404&t=1655975013375&host=t.locnavi.com",
      ],
    },
    "-20": {
      type: "vector",
      maxzoom: 19,
      tiles: [
        "https://map-1258113332.cos.ap-guangzhou.myqcloud.com/tiles_gcj02/珠海测试/-20/{z}/{x}/{y}.pbf?version=1655974980404&t=1655975013375&host=t.locnavi.com",
      ],
    },
    "outDoor-poi": {
      type: "vector",
      maxzoom: 17,
      tiles: [
        "http://localhost:5173/tile-map/map/poi/{z}/{x}/{y}.pbf?t=1655975013375&host=t.locnavi.com",
      ],
    },
    "outDoor-region": {
      type: "vector",
      maxzoom: 17,
      tiles: [
        "http://localhost:5173/tile-map/map/region/{z}/{x}/{y}.pbf?t=1655975013375&host=t.locnavi.com",
      ],
    },
    "centerPoint-source": {
      type: "geojson",
      data: {
        type: "FeatureCollection",
        features: [
          {
            type: "Feature",
            properties: {},
            geometry: {
              type: "Point",
              coordinates: [113.46762753351791, 22.203015332930853],
            },
          },
        ],
      },
    },
    "selected-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "marker-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "marker-active-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "route-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "parking-lot-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "gray-route-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "transfer-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "share-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "outDoorRoute-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "testPoint-source": {
      type: "geojson",
      data: { type: "FeatureCollection", features: [] },
    },
    "location-source": {
      type: "geojson",
      data: {
        type: "FeatureCollection",
        features: [
          {
            type: "Feature",
            properties: {
              icon_sails: "location_normal",
              render: "lv-location",
            },
            geometry: {
              coordinates: [113.30100812, 23.13195122],
              type: "Point",
            },
          },
        ],
      },
    },
  },
  layers: [
    {
      id: "base_fill_ground",
      type: "fill",
      source: "-20",
      "source-layer": "ground",
      filter: ["==", "render", "院内马路"],
      paint: {
        "fill-color": "#F6F6F6",
        "fill-opacity": ["get", "fill-opacity"],
      },
    },
    {
      id: "base_fill",
      type: "fill",
      source: "-20",
      "source-layer": "ground",
      filter: ["!=", "render", "院内马路"],
      paint: {
        "fill-color": [
          "match",
          ["get", "render"],
          "中空",
          "#F3F3F3",
          "停车",
          "#F1C3CA",
          "公共",
          "#E4C89C",
          "图标-大门",
          "#50A294",
          "图标-门",
          "#FFFFFF",
          "墙",
          "#F8F8F8",
          "外框",
          "#FFFFFF",
          "建筑",
          "#B8C8CE",
          "河",
          "#B9E3EC",
          "科室",
          "#50A294",
          "绿地",
          "#DDE6E9",
          "行政",
          "#9FDEDC",
          "覆盖",
          "#F3F3F3",
          "诊疗",
          "#9ECDF2",
          "转换",
          "#FFD6CE",
          "醒目",
          "#EDBECE",
          "醒目1",
          "#50A294",
          "院内马路",
          "#F6F6F6",
          "院外马路",
          "#A8B0B5",
          "隐藏区",
          "#D5DEE1",
          "#747474",
        ],
        "fill-opacity": ["get", "fill-opacity"],
      },
    },
    {
      id: "background_boundary",
      type: "line",
      source: "1",
      "source-layer": "outline",
      minzoom: 17,
      filter: ["all", ["!=", "show_region", "false"], ["==", "render", "外框"]],
      paint: {
        "line-color": "#7C8CAC",
        "line-opacity": {
          stops: [
            [17.5, 0],
            [18, 1],
          ],
        },
        "line-width": ["interpolate", ["linear"], ["zoom"], 0, 3, 15, 4, 22, 2],
      },
    },
    {
      id: "background_line",
      type: "line",
      source: "1",
      "source-layer": "outline",
      minzoom: 17.5,
      filter: ["all", ["!=", "show_region", "false"], ["==", "render", "外框"]],
      paint: {
        "line-color": "hsl(0, 0, 20%)",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          5,
          15,
          5,
          22,
          30,
        ],
        "line-blur": 50,
      },
    },
    {
      id: "background_fill",
      type: "fill",
      source: "1",
      "source-layer": "outline",
      minzoom: 17,
      filter: ["!=", "show_region", "false"],
      paint: {
        "fill-color": [
          "match",
          ["get", "render"],
          "中空",
          "#F3F3F3",
          "停车",
          "#F1C3CA",
          "公共",
          "#E4C89C",
          "图标-大门",
          "#50A294",
          "图标-门",
          "#FFFFFF",
          "墙",
          "#F8F8F8",
          "外框",
          "#FFFFFF",
          "建筑",
          "#B8C8CE",
          "河",
          "#B9E3EC",
          "科室",
          "#50A294",
          "绿地",
          "#DDE6E9",
          "行政",
          "#9FDEDC",
          "覆盖",
          "#F3F3F3",
          "诊疗",
          "#9ECDF2",
          "转换",
          "#FFD6CE",
          "醒目",
          "#EDBECE",
          "醒目1",
          "#50A294",
          "院内马路",
          "#F6F6F6",
          "院外马路",
          "#A8B0B5",
          "隐藏区",
          "#D5DEE1",
          "#747474",
        ],
        "fill-opacity": {
          stops: [
            [17, 0],
            [17.5, 1],
          ],
        },
      },
    },
    {
      id: "common_fill",
      type: "fill",
      source: "1",
      "source-layer": "plane",
      minzoom: 17,
      filter: [
        "all",
        ["==", "$type", "Polygon"],
        [
          "all",
          ["!=", "show_region", "false"],
          ["!=", "show_3D", true],
          ["!=", "fill-opacity", 0],
        ],
      ],
      paint: {
        "fill-color": [
          "match",
          ["get", "render"],
          "中空",
          "#F3F3F3",
          "停车",
          "#F1C3CA",
          "公共",
          "#E4C89C",
          "图标-大门",
          "#50A294",
          "图标-门",
          "#FFFFFF",
          "墙",
          "#F8F8F8",
          "外框",
          "#FFFFFF",
          "建筑",
          "#B8C8CE",
          "河",
          "#B9E3EC",
          "科室",
          "#50A294",
          "绿地",
          "#DDE6E9",
          "行政",
          "#9FDEDC",
          "覆盖",
          "#F3F3F3",
          "诊疗",
          "#9ECDF2",
          "转换",
          "#FFD6CE",
          "醒目",
          "#EDBECE",
          "醒目1",
          "#50A294",
          "院内马路",
          "#F6F6F6",
          "院外马路",
          "#A8B0B5",
          "隐藏区",
          "#D5DEE1",
          "#747474",
        ],
        "fill-opacity": {
          stops: [
            [17, 0],
            [17.5, 1],
          ],
        },
      },
    },
    {
      id: "zk_blur",
      type: "line",
      source: "1",
      "source-layer": "plane",
      minzoom: 17,
      filter: ["==", "render", "中空"],
      paint: {
        "line-color": "hsl(0, 0, 20%)",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          1,
          15,
          1,
          22,
          20,
        ],
        "line-blur": 50,
        "line-offset": 3,
        "line-opacity": {
          stops: [
            [17, 0],
            [17.5, 1],
          ],
        },
      },
    },
    {
      id: "common_line",
      type: "line",
      source: "1",
      "source-layer": "plane",
      minzoom: 17,
      filter: ["all", ["!=", "show_region", "false"], ["==", "render", "停车"]],
      paint: { "line-color": "#EEEEEE" },
    },
    {
      id: "3D_line",
      type: "line",
      source: "1",
      "source-layer": "room",
      minzoom: 18,
      filter: [
        "all",
        ["!=", "show_region", "false"],
        ["==", "show_3D", true],
        ["in", "$type", "LineString", "Polygon"],
      ],
      paint: {
        "line-color": "#000",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          0,
          15,
          0,
          18,
          1,
          22,
          12,
        ],
        "line-blur": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          0,
          15,
          0,
          18,
          30,
          22,
          80,
        ],
        "line-height": 0,
      },
    },
    {
      id: "3D_fill",
      type: "fill-extrusion",
      source: "1",
      "source-layer": "room",
      minzoom: 17,
      filter: [
        "all",
        ["==", "$type", "Polygon"],
        ["all", ["!=", "show_region", "false"], ["==", "show_3D", true]],
      ],
      paint: {
        "fill-extrusion-color": [
          "match",
          ["get", "render"],
          "中空",
          "#F3F3F3",
          "停车",
          "#F1C3CA",
          "公共",
          "#E4C89C",
          "图标-大门",
          "#50A294",
          "图标-门",
          "#FFFFFF",
          "墙",
          "#F8F8F8",
          "外框",
          "#FFFFFF",
          "建筑",
          "#B8C8CE",
          "河",
          "#B9E3EC",
          "科室",
          "#50A294",
          "绿地",
          "#DDE6E9",
          "行政",
          "#9FDEDC",
          "覆盖",
          "#F3F3F3",
          "诊疗",
          "#9ECDF2",
          "转换",
          "#FFD6CE",
          "醒目",
          "#EDBECE",
          "醒目1",
          "#50A294",
          "院内马路",
          "#F6F6F6",
          "院外马路",
          "#A8B0B5",
          "隐藏区",
          "#D5DEE1",
          "#747474",
        ],
        "fill-extrusion-opacity": {
          stops: [
            [17, 0],
            [17.5, 0.9],
          ],
        },
        "fill-extrusion-height": ["get", "fill-3D-height"],
        "fill-extrusion-base": 0,
      },
    },
    {
      id: "textIcon_symbol",
      type: "symbol",
      source: "1",
      "source-layer": "symbol",
      minzoom: 18.5,
      filter: ["all", ["==", "$type", "Point"], ["!=", "show_3D", true]],
      layout: {
        "text-font": ["notosansscregular"],
        "text-field": "{label}",
        "text-size": 12,
        "icon-image": "{icon_sails}",
        "icon-size": 0.8,
        "icon-offset": [0, -20],
      },
      paint: {
        "text-color": "#747474",
        "text-halo-width": 1.5,
        "text-halo-color": "#FFFFFF",
      },
    },
    {
      id: "3D_textIcon_symbol",
      type: "symbol",
      source: "1",
      "source-layer": "symbol",
      minzoom: 18.5,
      filter: ["all", ["==", "$type", "Point"], ["==", "show_3D", true]],
      layout: {
        "text-font": ["notosansscregular"],
        "text-field": "{label}",
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          10,
          18,
          11,
          22,
          16,
        ],
        "icon-image": "{icon_sails}",
        "icon-size": 0.8,
        "icon-offset": [0, -20],
      },
      paint: {
        "text-color": "#747474",
        "text-halo-width": 1.5,
        "text-halo-color": "#FFFFFF",
        "text-height": 0.9,
        "icon-height": 0.9,
      },
    },
    {
      id: "area_symbol",
      type: "symbol",
      source: "1",
      "source-layer": "area",
      minzoom: 17,
      maxzoom: 18.5,
      layout: {
        "text-font": ["notosansscregular"],
        "text-field": "{label}",
        "text-size": 14,
        "icon-image": "{icon_sails}",
        "icon-size": 0.8,
        "icon-offset": [0, -20],
      },
      paint: {
        "text-color": "#747474",
        "text-halo-width": 1.5,
        "text-halo-blur": 2,
        "text-halo-color": "#FFFFFF",
        "text-opacity": {
          stops: [
            [17, 0],
            [17.5, 1],
          ],
        },
      },
    },
    {
      id: "base_symbol",
      type: "symbol",
      source: "-20",
      "source-layer": "symbol",
      minzoom: 15,
      filter: ["all", ["==", "$type", "Point"], ["!=", "render", "建筑"]],
      layout: {
        "text-font": ["notosansscregular"],
        "text-field": "{label}",
        "text-size": 15,
        "icon-image": "{icon_sails}",
        "icon-size": 0.8,
        "icon-offset": [0, -20],
      },
      paint: {
        "text-color": {
          type: "categorical",
          property: "render",
          stops: [
            ["公共", "#697B8D"],
            ["图标-大门", "#656E85"],
            ["图标-门", "#656E85"],
            ["建筑", "#74879B"],
            ["行政", "#4F929F"],
            ["诊疗", "#3D82A5"],
            ["醒目", "#D267A7"],
            ["院外马路", "#868686"],
          ],
          default: "#747474",
        },
        "text-halo-width": 1.5,
        "text-halo-blur": 0.5,
        "text-halo-color": "#FFFFFF",
      },
    },
    {
      id: "base_3D",
      type: "fill-extrusion",
      source: "-20",
      "source-layer": "ground",
      maxzoom: 17.5,
      filter: ["==", "show_3D", true],
      paint: {
        "fill-extrusion-color": "#C6DAED",
        "fill-extrusion-opacity": {
          stops: [
            [17, 0.93],
            [17.5, 0],
          ],
        },
        "fill-extrusion-height": ["get", "fill-3D-height"],
        "fill-extrusion-base": 0,
      },
    },
    {
      id: "building_symbol",
      type: "symbol",
      source: "-20",
      "source-layer": "symbol",
      minzoom: 14,
      maxzoom: 18.5,
      filter: ["all", ["==", "$type", "Point"], ["==", "render", "建筑"]],
      layout: {
        "text-font": ["notosansscregular"],
        "text-field": "{label}",
        "text-size": 16.5,
        "icon-image": "{icon_sails}",
        "icon-size": 0.8,
        "icon-offset": [0, -20],
      },
      paint: {
        "text-color": "#74879B",
        "text-halo-width": 1.5,
        "text-halo-blur": 2,
        "text-halo-color": "#FFFFFF",
      },
    },
  ],
};
