export default [
  {
    id: "base_fill_ground",
    type: "fill",
    source: "-20",
    "source-layer": "ground",
    filter: ["==", "render", "院内马路"],
    paint: { "fill-color": "#F6F6F6", "fill-opacity": ["get", "fill-opacity"] },
  },
  {
    id: "base_fill",
    type: "fill",
    source: "-20",
    "source-layer": "ground",
    filter: ["!=", "render", "院内马路"],
    paint: {
      "fill-color": [
        "match",
        ["get", "render"],
        "中空",
        "#F3F3F3",
        "停车",
        "#F1C3CA",
        "公共",
        "#E4C89C",
        "图标-大门",
        "#50A294",
        "图标-门",
        "#FFFFFF",
        "墙",
        "#F8F8F8",
        "外框",
        "#FFFFFF",
        "建筑",
        "#B8C8CE",
        "河",
        "#B9E3EC",
        "科室",
        "#50A294",
        "绿地",
        "#DDE6E9",
        "行政",
        "#9FDEDC",
        "覆盖",
        "#F3F3F3",
        "诊疗",
        "#9ECDF2",
        "转换",
        "#FFD6CE",
        "醒目",
        "#EDBECE",
        "醒目1",
        "#50A294",
        "院内马路",
        "#F6F6F6",
        "院外马路",
        "#A8B0B5",
        "隐藏区",
        "#D5DEE1",
        "#747474",
      ],
      "fill-opacity": ["get", "fill-opacity"],
    },
  },
  {
    id: "base_symbol",
    type: "symbol",
    source: "-20",
    "source-layer": "symbol",
    minzoom: 15,
    filter: ["all", ["==", "$type", "Point"], ["!=", "render", "建筑"]],
    layout: {
      "text-font": ["notosansscregular"],
      "text-field": "{label}",
      "text-size": 15,
      "icon-image": "{icon_sails}",
      "icon-size": 0.8,
      "icon-offset": [0, -20],
    },
    paint: {
      "text-color": {
        type: "categorical",
        property: "render",
        stops: [
          ["公共", "#697B8D"],
          ["图标-大门", "#656E85"],
          ["图标-门", "#656E85"],
          ["建筑", "#74879B"],
          ["行政", "#4F929F"],
          ["诊疗", "#3D82A5"],
          ["醒目", "#D267A7"],
          ["院外马路", "#868686"],
        ],
        default: "#747474",
      },
      "text-halo-width": 1.5,
      "text-halo-blur": 0.5,
      "text-halo-color": "#FFFFFF",
    },
  },
  {
    id: "base_3D",
    type: "fill-extrusion",
    source: "-20",
    "source-layer": "ground",
    maxzoom: 17.5,
    filter: ["==", "show_3D", true],
    paint: {
      "fill-extrusion-color": "#C6DAED",
      "fill-extrusion-opacity": {
        stops: [
          [17, 0.93],
          [17.5, 0],
        ],
      },
      "fill-extrusion-height": ["get", "fill-3D-height"],
      "fill-extrusion-base": 0,
    },
  },
  {
    id: "building_symbol",
    type: "symbol",
    source: "-20",
    "source-layer": "symbol",
    minzoom: 14,
    maxzoom: 18.5,
    filter: ["all", ["==", "$type", "Point"], ["==", "render", "建筑"]],
    layout: {
      "text-font": ["notosansscregular"],
      "text-field": "{label}",
      "text-size": 16.5,
      "icon-image": "{icon_sails}",
      "icon-size": 0.8,
      "icon-offset": [0, -20],
    },
    paint: {
      "text-color": "#74879B",
      "text-halo-width": 1.5,
      "text-halo-blur": 2,
      "text-halo-color": "#FFFFFF",
    },
  },
];
